name: ReleaseBuild
on:
  push:
    branches:
      - main
env:
  SOLUTION_FILE_PATH: Engine/GameEngine_DX12.sln
  CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
          vs-version: 'latest'

      - name: Verify MSVC version
        run: |
          cl
          msbuild /version

      - name: Build
        run: |
          msbuild ${{env.SOLUTION_FILE_PATH}} /p:Platform=x64,Configuration=${{env.CONFIGURATION}}
